services:
  sensors:
    build:
      context: .
      dockerfile: Dockerfile
    image: icp10125_scd4x_mqtt:latest
    container_name: sensors
    restart: unless-stopped
    devices:
      - /dev/i2c-1:/dev/i2c-1
